#!/usr/bin/env python3

"""
builpy
"""

from _builpy import dbg

from _builpy.check import pkg_check, src_check
from _builpy.vcs import get_source, src_update, src_export

from _builpy.cli import PACKAGES
from _builpy.spec import spec_update, spec_bump

from _builpy.rpm import rpmbuild_create_dirs, rpmbuild_remove_dirs
from _builpy.rpm import rpmbuild_copy_sources, rpmbuild_build_srpm

from _builpy.copr import copr_build


for package in PACKAGES:
    dbg("Checking: " + package)
    pkg_check(package)

    dbg("Checking sources: " + package)
    pkgsources = src_check(package)

    if not pkgsources:
        dbg("Getting sources: " + package)
        get_source(package)

    dbg("Getting updates: " + package)
    pkgupdate = src_update(package)

    if pkgupdate or not pkgsources:
        dbg("Updating spec file: " + package)
        spec_update(package)
        dbg("Bumping spec file: " + package)
        spec_bump(package, "Update to new upstream snapshot.")

        dbg("Exporting source: " + package)
        src_export(package)

        dbg("Creating rpmbuild directories.")
        rpmbuild_create_dirs()
        dbg("Copying sources.")
        rpmbuild_copy_sources(package)
        dbg("Building srpms.")
        rpmbuild_build_srpm(package)
        dbg("Uploading and building in copr.")
        copr_build(package)
        dbg("Removing rpmbuild directories.")
        rpmbuild_remove_dirs()

